sources:
  - name: main
    tables:
      - name: bird_toots
      - name: tickets
      - name: birds
      - name: sites
      - name: species
      - name: lake_river_flow
      - name: lake_river_sites